// demo/src/components/ArticleCard.tsx
import { Link } from "@contentstech/stackflow-link/future";
import { LazyLoadImage } from "react-lazy-load-image-component";
import * as css from "./ArticleCard.css";

interface ArticleCardProps {
  articleId: string;
  title: string;
  price: number;
}
const ArticleCard: React.FC<ArticleCardProps> = ({
  articleId,
  title,
  price,
}) => {
  const imageUrl = `https://picsum.photos/800/800/?id=${articleId}`;

  return (
    <Link
      activityName="Article"
      activityParams={{ articleId: String(articleId), title }}
      className={css.container}
    >
      <div className={css.thumbnail}>
        <div className={css.innerImage}>
          <LazyLoadImage
            src={imageUrl}
            effect="opacity"
            width="100%"
            height="100%"
          />
        </div>
      </div>
      <div className={css.title}>{title}</div>
      <div className={css.price}>£{price}.00</div>
    </Link>
  );
};

export default ArticleCard;

// demo-solid/src/components/ArticleCard.tsx
import { useFlow } from "@contentstech/stackflow-solid/future";
import { type Component, createMemo } from "solid-js";
import * as css from "./ArticleCard.css";

interface ArticleCardProps {
  articleId: string;
  title: string;
  price: number;
}
const ArticleCard: Component<ArticleCardProps> = (props) => {
  const { push } = useFlow();

  const imageUrl = createMemo(
    () => `https://picsum.photos/800/800/?id=${props.articleId}`,
  );

  const onClick = () => {
    push("Article", {
      articleId: String(props.articleId),
      title: props.title,
    });
  };

  return (
    <button type="button" class={css.container} onClick={onClick}>
      <div class={css.thumbnail}>
        <div class={css.innerImage}>
          <img src={imageUrl()} alt={props.title} width="100%" height="100%" />
        </div>
      </div>
      <div class={css.title}>{props.title}</div>
      <div class={css.price}>£{props.price}.00</div>
    </button>
  );
};

export default ArticleCard;
